### ISSUE TITLE
`.travis.yml` ssh key shenanigans

### ISSUE THREAD

**Issue by emory** [lefant/ng-flickrdupfinder#5]
FYI; `.travis.yml` in your repository has some ssh key juggling that you may or may not care to have public.

**Comment by lefant** [comment]
I have a dedicated ssh key which is only allowed to deploy. The private key is checked into the repo encrypted with a key that only travis has access to. The .travis.yml config are instructions for travis to decrypt the key in order to be able to push the deploy. They have some docs about this stuff here: http://docs.travis-ci.com/user/encrypting-files/

Anyway, it is fully intentional, thanks for your caring! I hope you enjoy the ng-flickrdupfinder source code! ;)

Fabian
